// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQV079Y11aP76Rsd9NJBtPCJXaWgNLkk',
    appId: '1:850002986710:web:89a43e5897ac2150286b77',
    messagingSenderId: '850002986710',
    projectId: 'quitandavirtual',
    authDomain: 'quitandavirtual.firebaseapp.com',
    storageBucket: 'quitandavirtual.firebasestorage.app',
    measurementId: 'G-DVZWQKSHYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWFR4-1xaI453VQO31kTMtuO_RvJLY8W8',
    appId: '1:850002986710:android:40c94146cd819ef8286b77',
    messagingSenderId: '850002986710',
    projectId: 'quitandavirtual',
    storageBucket: 'quitandavirtual.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFAj9klJ-OGmDZIydh4r-r_Dv98Sp7OM',
    appId: '1:850002986710:ios:b0c444fe0a9ac27c286b77',
    messagingSenderId: '850002986710',
    projectId: 'quitandavirtual',
    storageBucket: 'quitandavirtual.firebasestorage.app',
    iosBundleId: 'com.example.greengrocer',
  );
}
